[tool.poetry]
name = "discrete-signals"
version = "0.7.3"
description = "A domain specific language for modeling and manipulating discrete time signals."
authors = ["Marcell Vazquez-Chanlatte <mvc@linux.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^19.3.0"
funcy = "^1.14"
sortedcontainers = "^2.1.0"
pytest-xdist = "^1.31.0"
pytest-sugar = "^0.9.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
codecov = "^2.0.15"
pytest-flake8 = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
